# Start with a base image containing Java runtime
#FROM openjdk:8
FROM hello-world
# Add a volume pointing to /tmp
VOLUME /tmp
# Make port 8081 available to the world outside this container
EXPOSE 8090
# The application's jar file  
#ARG JAR_FILE=target/hello-world.jar
ARG JAR_FILE
# Add the application's jar to the container
ADD ${JAR_FILE} /var/lib/jenkins/workspace/Build_Image/test
#COPY ${JAR_FILE} /var/lib/jenkins/workspace/Test_Job/test/
#  Run the jar file 
ENTRYPOINT ["java","-jar","/hello-world.jar"]
