pipeline { 
    agent any  
    stages { 
        stage('test') { 
            steps { 
                sh 'mvn test'
               echo 'This is a minimal pipeline.' 
            }
        }
    }
}
